name: Create JIRA issue on GitHub issue creation

on:
  issues:
    types: [opened]

jobs:
  create-jira-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create JIRA issue
        uses: actions/github-script@v7
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
        with:
          script: |
            const issue = context.payload.issue;
            const fetch = require('node-fetch');

            const auth = Buffer.from(`${process.env.JIRA_EMAIL}:${process.env.JIRA_API_TOKEN}`).toString('base64');
            const response = await fetch(`${process.env.JIRA_BASE_URL}/rest/api/3/issue`, {
              method: 'POST',
              headers: {
                'Authorization': `Basic ${auth}`,
                'Accept': 'application/json',
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                fields: {
                  project: {
                    key: process.env.JIRA_PROJECT_KEY
                  },
                  summary: issue.title,
                  description: issue.body || "No description provided.",
                  issuetype: {
                    name: "Task"
                  }
                }
              })
            });

            if (!response.ok) {
              const text = await response.text();
              core.setFailed(`Failed to create JIRA issue: ${response.status} ${text}`);
            } else {
              const data = await response.json();
              core.info(`JIRA issue created: ${data.key}`);
            }
